### ISSUE TITLE
MD5::MD5-STATE-REGS not found 

### ISSUE THREAD

**Issue by fourier** [pmai/md5#2]
With SBCL 1.3.2 on OSX cannot use the library: 

``` lisp
(md5:md5sum-file "/Users/user/filename")
```

produces the error

```
 The function MD5::MD5-STATE-REGS is undefined.
   [Condition of type UNDEFINED-FUNCTION]
```

**Comment by pmai** [comment]
Hmmm, I haven't been able to replicate this problem on either 1.2.11 on OSX/amd64 or 1.3.3 on Windows/amd64 (which are the only official builds I have access to, at the moment); it would also seem to be a strange error, indicating either a broken sbcl or some form of build failure, since the md5-state structure is defined in the same file and there are no conditionals involved...

Which platform of sbcl are you using (amd64 or x86 or ppc?), and which version of md5 are you using, and how do you build and load it (manually, via ASDF, via Quicklisp, ...)? Can you provide the compiler output when compiling md5.lisp?

**Comment by fourier** [comment]
Nevermind, I used a locally cloned version and probably messed with somethings. Removed local version and reinstalled from QucikLisp and everything is fine. I'm closing the issue.
